// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkYIV90PhlDFCc7p364Mgh2Z_HeN7smuI',
    appId: '1:728223381124:web:d67033a3332e7f894774d1',
    messagingSenderId: '728223381124',
    projectId: 'flutter-car-rental-5e922',
    authDomain: 'flutter-car-rental-5e922.firebaseapp.com',
    storageBucket: 'flutter-car-rental-5e922.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGJt5w39N3TCjUnYThYnZP8LTyzGhMhb0',
    appId: '1:728223381124:android:e191cd7c5a7ba0cb4774d1',
    messagingSenderId: '728223381124',
    projectId: 'flutter-car-rental-5e922',
    storageBucket: 'flutter-car-rental-5e922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhAv9CZmHps98Or1Z4jzuggGwrMdcUx20',
    appId: '1:728223381124:ios:8131f1c6c7b65dca4774d1',
    messagingSenderId: '728223381124',
    projectId: 'flutter-car-rental-5e922',
    storageBucket: 'flutter-car-rental-5e922.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhAv9CZmHps98Or1Z4jzuggGwrMdcUx20',
    appId: '1:728223381124:ios:8131f1c6c7b65dca4774d1',
    messagingSenderId: '728223381124',
    projectId: 'flutter-car-rental-5e922',
    storageBucket: 'flutter-car-rental-5e922.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkYIV90PhlDFCc7p364Mgh2Z_HeN7smuI',
    appId: '1:728223381124:web:c14a33c16c8684dd4774d1',
    messagingSenderId: '728223381124',
    projectId: 'flutter-car-rental-5e922',
    authDomain: 'flutter-car-rental-5e922.firebaseapp.com',
    storageBucket: 'flutter-car-rental-5e922.appspot.com',
  );
}
